// <auto-generated />
namespace TrackerApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_connections_ids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_connections_ids));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131217058_add_connections_ids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
